In [1]:
print("Hello from Jupyter")
print("I am learning Bioinformatics")

Hello from Jupyter
I am learning Bioinformatics


In [2]:
import numpy as np
print("NumPy imported successfully!")
print("Version:", np.__version__)

NumPy imported successfully!
Version: 2.4.6


In [3]:
#Numpy is a array like 96 plate which holds hundreds of values and lets you do calculations on all of them at once
#Step 1 creating a NumPy array
gene_expression_list = [2.5, 3.1, 1.8, 4.2, 3.7] #Normal python list
gene_expression_array = np.array([2.5, 3.1, 1.8, 4.2, 3.7])
print("List:", gene_expression_list)
print("Array:", gene_expression_array)
print("Type:", type(gene_expression_array))

List: [2.5, 3.1, 1.8, 4.2, 3.7]
Array: [2.5 3.1 1.8 4.2 3.7]
Type: <class 'numpy.ndarray'>


In [4]:
#Step 2 
import numpy as np
gene_expressions = np.array([2.5, 3.1, 1.8, 4.2, 3.7])
print("Mean expressions:", np.mean(gene_expressions))
print("Max expressions:", np.max(gene_expressions))
print("Min expressions:", np.min(gene_expressions))
print("Total:", np.sum(gene_expressions))



Mean expressions: 3.06
Max expressions: 4.2
Min expressions: 1.8
Total: 15.3


In [5]:
#Step 3 array operations
import numpy as np
patient1 = np.array([2.5, 3.1, 1.8, 4.2, 3.7])
patient2 = np.array([1.5, 2.1, 3.8, 2.2, 4.7])
print("Patient1 mean:", np.mean(patient1))
print("Patient2 mean:", np.mean(patient2))
difference = patient1 - patient2
print("Difference:", difference)
print("Higher in patient 1:", patient1 > patient2)

Patient1 mean: 3.06
Patient2 mean: 2.8600000000000003
Difference: [ 1.  1. -2.  2. -1.]
Higher in patient 1: [ True  True False  True False]


In [7]:
#Step 4 filtering arrays
import numpy as np
gene_expression = np.array([2.5, 3.1, 1.8, 4.2, 3.7, 0.5, 4.8, 1.2])
high_expression = gene_expression[gene_expression > 3.0]
print("All expressions:", gene_expression)
print("Highly expressed genes:", high_expression)
print("Count of high expressions:", len(high_expression))



All expressions: [2.5 3.1 1.8 4.2 3.7 0.5 4.8 1.2]
Highly expressed genes: [3.1 4.2 3.7 4.8]
Count of high expressions: 4


In [9]:
#step 5 2D arrays
import numpy as np
expression_data = np.array([
    [2.5, 3.1, 1.8, 4.2], #Patient 1
    [1.5, 2.1, 3.8, 2.2], #Patient 2
    [3.5, 4.1, 2.8, 1.2]#patient 3
])
print("All data:\n", expression_data)
print("Shape:", expression_data.shape)
print("Patient 1 data:", expression_data[0])
print("Gene 1 all patients:", expression_data[:,0])

All data:
 [[2.5 3.1 1.8 4.2]
 [1.5 2.1 3.8 2.2]
 [3.5 4.1 2.8 1.2]]
Shape: (3, 4)
Patient 1 data: [2.5 3.1 1.8 4.2]
Gene 1 all patients: [2.5 1.5 3.5]


In [10]:
#Statistics on 2D array
import numpy as np
expression_data = np.array([
    [2.5, 3.1, 1.8, 4.2],
    [1.5, 2.1, 3.8, 2.2],
    [3.5, 4.1, 2.8, 1.2]
])
print("Mean per patient:", np.mean(expression_data, axis=1))
print("Mean per gene:", np.mean(expression_data, axis=0))
print("Lowest expression:", np.min(expression_data))
print("Highest expression:", np.max(expression_data))
print("Standard deviation:", round(np.std(expression_data),2))


Mean per patient: [2.9 2.4 2.9]
Mean per gene: [2.5        3.1        2.8        2.53333333]
Lowest expression: 1.2
Highest expression: 4.2
Standard deviation: 0.97


In [2]:
#Exercise 1
import numpy as np
protein = np.array([45.2, 12.8, 78.3, 23.1, 56.7, 34.5])
large_proteins = protein[protein > 40]
print("All expressions:", protein)
print("Mean:", np.mean(protein))
print("Max:", np.max(protein))
print("Min:", np.min(protein))
print("Larger than 40kDA:", large_proteins)
print("Count of high expressions:", len(large_proteins))


All expressions: [45.2 12.8 78.3 23.1 56.7 34.5]
Mean: 41.76666666666667
Max: 78.3
Min: 12.8
Larger than 40kDA: [45.2 78.3 56.7]
Count of high expressions: 3


In [3]:
import numpy as np
expression_data = np.array([
    [1.2, 2.3, 3.4],
    [4.5, 5.6, 6.7],
    [7.8, 8.9, 9.0]
])
print("All data:\n", expression_data)
print("Shape:", expression_data.shape)
print("Mean per gene:", np.mean(expression_data, axis=0))
print("Highest expression:", np.max(expression_data))


All data:
 [[1.2 2.3 3.4]
 [4.5 5.6 6.7]
 [7.8 8.9 9. ]]
Shape: (3, 3)
Mean per gene: [4.5        5.6        6.36666667]
Highest expression: 9.0


In [4]:
import numpy as np
gc_percentage = np.array([45.0, 62.3, 38.7, 71.2, 55.8])
larger_sequences = gc_percentage[gc_percentage > 50]
print("Large sequences of GC:", larger_sequences)
print("Count of large sequences of GC:", len(larger_sequences))
print("Mean of GC percentage:", np.mean(gc_percentage))

Large sequences of GC: [62.3 71.2 55.8]
Count of large sequences of GC: 3
Mean of GC percentage: 54.6
